name: Django heaven tests

on:
  push:
    branches:
    - master
  pull_request:
  workflow_run:

jobs:
  tests:
    name: Test on python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install requirements.txt

    - name: Run tests
      run: python manage.py test
